spring:
  application:
    name: bank.rest
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/bank-cards}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

app:
  security:
    secret: ${SECURITY_SECRET:d534560ff5c15803a1185f93d271ec7e}

server:
  servlet:
    contextPath: /
  port: 8080